version: '2'

services:
  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"

    labels:
      NAME: "rabbitmq1"

  web:
    build: .
    command: bash runserver.sh
    volumes:
      - .:/code
    ports:
      - "8081:8081"
      - "5555:5555"

    depends_on:
      - rabbit1

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit1
      - web
    depends_on:
      - rabbit1

